#!/usr/bin/env python
"""Assemble the deployable static site from the warehouse export.

Produces a self-contained ``site/`` directory: no build step, no runtime data
fetch, no external CDN. It can be served from a file path, uploaded to
Cloudflare Pages as static assets, or opened straight from disk.

The data payload is written as ``window.__DATA__`` rather than fetched, so the
page works offline and under a strict Content-Security-Policy with no
connect-src requirement.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

SITE = ROOT / "site"
EXPORT = ROOT / "data" / "export" / "site" / "data.json"


def build() -> int:
    if not EXPORT.exists():
        raise SystemExit(
            f"{EXPORT} not found. Run 'PYTHONPATH=src python -m "
            f"src.dashboard.export' first."
        )
    payload = json.loads(EXPORT.read_text())
    (SITE / "assets").mkdir(parents=True, exist_ok=True)

    # Assigned as a global rather than fetched, so the page needs no network.
    js = (
        "/* Generated by scripts/build_site.py. Do not edit by hand. */\n"
        "window.__DATA__ = " + json.dumps(payload, separators=(",", ":")) + ";\n"
    )
    (SITE / "assets" / "data.js").write_text(js)

    for name in ("index.html",):
        if not (SITE / name).exists():
            raise SystemExit(f"missing template: {SITE / name}")

    size = (SITE / "assets" / "data.js").stat().st_size
    print(f"site assembled at {SITE}")
    print(f"  data payload   {size:,} bytes")
    print(f"  files          {[p.name for p in sorted(SITE.glob('*.html'))]}")
    print("\nserve locally with:")
    print(f"  {ROOT / '.venv' / 'bin' / 'python'} -m http.server --directory {SITE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(build())