#!/usr/bin/env python
"""Assemble the deployable static site from the warehouse export.

Produces a self-contained ``site/`` directory: no build step, no runtime data
fetch, no external CDN. It can be served from a file path, uploaded to
Cloudflare Pages as static assets, or opened straight from disk.

The data payload is written as ``window.__DATA__`` rather than fetched, so the
page works offline and under a strict Content-Security-Policy with no
connect-src requirement.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

SITE = ROOT / "site"
EXPORT = ROOT / "data" / "export" / "site" / "data.json"

# Every place the repository states how many tests it has, as (file, pattern,
# replacement). The number is collected from pytest rather than written by hand:
# a hardcoded count goes stale the week a test is added, and a count is a claim a
# reviewer can check. Each pattern is anchored so it can only ever touch its own
# sentence, and each also matches the number a previous build substituted, so
# rebuilding refreshes rather than accumulates.
COUNT_SITES: tuple[tuple[Path, re.Pattern[str], str], ...] = (
    (
        SITE / "index.html",
        re.compile(
            r"(quality gate on every build)(?:\{\{TEST_COUNT\}\}|, \d[\d,]* tests)?"
        ),
        r"\g<1>, {n} tests",
    ),
    (
        ROOT / "README.md",
        re.compile(r"(make test\s+# )\d[\d,]*( tests)"),
        r"\g<1>{n}\g<2>",
    ),
    (
        ROOT / "README.md",
        re.compile(r"(^\s*tests/\s+)\d[\d,]*( tests)", re.M),
        r"\g<1>{n}\g<2>",
    ),
)


def collect_test_count() -> int | None:
    """Number of tests pytest collects, or None if that could not be measured."""
    try:
        out = subprocess.run(
            [sys.executable, "-m", "pytest", "--collect-only", "-q", "--no-header"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=300,
        )
    except Exception as exc:  # noqa: BLE001 - a missing pytest must not break the build
        print(f"test count unavailable ({exc})")
        return None
    if out.returncode != 0:
        print(f"test count unavailable: {out.stderr.strip()[-300:]}")
        return None
    # Summary line reads e.g. "313 tests collected in 0.42s".
    match = re.search(r"^(\d+) tests? collected", out.stdout, re.MULTILINE)
    if not match:
        print(f"test count unavailable: {out.stdout.strip()[-300:]}")
        return None
    return int(match.group(1))


def refresh_test_count(count: int | None) -> None:
    """Write the collected test count into every file that quotes it."""
    for path, pattern, template in COUNT_SITES:
        text = path.read_text(encoding="utf-8")
        if not pattern.search(text):
            continue
        if count is None:
            # Never ship a literal placeholder, and never claim a number we
            # did not measure. Drop the clause instead.
            repl = ""
        else:
            repl = template.replace("{n}", f"{count:,}")
        path.write_text(pattern.sub(repl, text), encoding="utf-8")
    print(f"  test count     {count:,}" if count else "  test count     unavailable")


def build() -> int:
    if not EXPORT.exists():
        raise SystemExit(
            f"{EXPORT} not found. Run 'PYTHONPATH=src python -m "
            f"src.dashboard.export' first."
        )
    payload = json.loads(EXPORT.read_text())
    (SITE / "assets").mkdir(parents=True, exist_ok=True)

    # Assigned as a global rather than fetched, so the page needs no network.
    js = (
        "/* Generated by scripts/build_site.py. Do not edit by hand. */\n"
        "window.__DATA__ = " + json.dumps(payload, separators=(",", ":")) + ";\n"
    )
    (SITE / "assets" / "data.js").write_text(js)

    for name in ("index.html",):
        if not (SITE / name).exists():
            raise SystemExit(f"missing template: {SITE / name}")

    refresh_test_count(collect_test_count())

    size = (SITE / "assets" / "data.js").stat().st_size
    print(f"site assembled at {SITE}")
    print(f"  data payload   {size:,} bytes")
    print(f"  files          {[p.name for p in sorted(SITE.glob('*.html'))]}")
    print("\nserve locally with:")
    print(f"  {ROOT / '.venv' / 'bin' / 'python'} -m http.server --directory {SITE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(build())